/**
 * Inventra — App Footer
 * Used only inside AppLayout (authenticated pages) and print reports.
 * NOT shown on login / register / change-password pages.
 */

interface FooterProps {
  printMode?: boolean;
}

export default function Footer({ printMode = false }: FooterProps) {
  if (printMode) {
    return (
      <div className="print-footer" style={{ display: 'none' }}>
        Generated by Inventra ERP &nbsp;|&nbsp; Developed &amp; Maintained by Asad Hamdan &nbsp;|&nbsp; +91 93425 09303
      </div>
    );
  }

  return (
    <footer className="flex-shrink-0 w-full py-2 px-4 text-center border-t border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900">
      <p className="text-[10px] text-gray-400 dark:text-gray-600 font-medium tracking-wide">
        © {new Date().getFullYear()} Inventra ERP
        &nbsp;·&nbsp;
        Developed &amp; Maintained by{' '}
        <span className="text-gray-500 dark:text-gray-500 font-semibold">Asad Hamdan</span>
        {' '}|{' '}
        <a
          href="tel:+919342509303"
          className="text-gray-500 dark:text-gray-500 hover:text-indigo-500 dark:hover:text-indigo-400 transition-colors"
        >
          +91 93425 09303
        </a>
      </p>
    </footer>
  );
}
